<template>
  <div>
    <!--    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 500 289"
      xml:space="preserve"
      class="fill-current regular-text h-10"
    >
      <path
        d="M323.7 223.3h-5.8l-.1.1-46-.3-35-.2h-.3l86.6-124.1 21.8-31.3 24.2-34.7h-22.5l-304.8-.4L79.7 71l210.8.4L185.2 224l-25.5 37-.4.5h176.1l.2-.1h115.6l34.7-38.1h-29.8z"
      />
      <path
        d="M214 128.6H75.8l-33 37.2h141.6zM311.7 165.8h114.8l29.6-37.2H337.5zM487 32.4h-81.3l-25.8 37.2h77.5zM12.6 261.2h117.6l24.6-37.2H40z"
      />
    </svg>-->
    <!--    animated logo-->
    <router-link :to="{ name: 'Home' }">
      <svg viewBox="0 0 442 207" class="h-10 pl-4 fill-red-500">
        <path
          d="m25.21 121.97-.24.28-20.38-18.32.24-.26z"
          class="svg-elem-1"
        ></path>
        <path
          d="m76.48 64.91-32.13 35.76 32.13 28.86v38.49l-51.27-46.05-20.38-18.3-1.18-1.07 72.52-80.73.31.27z"
          class="svg-elem-2"
        ></path>
        <path
          d="M76.48 168.02v.49l-51.51-46.26-20.38-18.32.24-.26 20.38 18.3z"
          class="svg-elem-3"
        ></path>
        <path
          d="M76.48 168.02v.49l-51.51-46.26-20.38-18.32.24-.26 20.38 18.3zM95.08 184H341v12H95.08zM127 24.3v76.66l-32 44.15V24.3zm214 143.53h-4.15L340 172h-40.37l-20.02-26.54-37.52-49.75V42.18L314 137.53v3.3h2.49l-2.49-3.3V21.87h27z"
          class="svg-elem-4"
        ></path>
        <path
          d="M316.49 140.83H314v-3.3zm24.51 27V172h-1l-3.15-4.17zm93.5-78.97-72.72 80.56-.3-.27.1-42.76 32.21-35.69-32.06-28.94.09-38.49 51.16 46.17 20.34 18.35zM226.75 23.4l-.2-.27-.2-.26h-38.86l-.69 1.07-91.72 142.7 2.6 2.19h35.6L164.02 121H203v47.83h24.09v-145l-.34-.43zM203 99.87h-25.4L203 60.35v39.52z"
          class="svg-elem-5"
        ></path>
      </svg>
    </router-link>
  </div>
</template>

<style>
/***************************************************
 * Generated by SVG Artista on 9/19/2022, 4:44:36 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
    0.8s both;
  animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s
    both;
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
    0.9s both;
  animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s
    both;
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
    1s both;
  animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
    1.1s both;
  animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s
    both;
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(236, 7, 7);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
    1.2000000000000002s both;
  animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
    1.2000000000000002s both;
}
</style>
